describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:8080')
    cy.get(':nth-child(1) > .control > .input').type("kanto@etu.univ-tours.fr")
    cy.get(':nth-child(2) > .control > .input').type("MaCouille")
    cy.get('form').submit()
    cy.get('ul > :nth-child(1) > a').click()
    cy.get('.button').click()
    cy.get('#email').type("aaaaaaa@gmail.com")
    cy.get('#password').type("coucou")
    cy.get('#firstName').type("coucou")
    cy.get('#lastName').type("coucou")
    cy.get('#department').select(0)
    cy.get('form').submit()
    cy.wait(1000)
    //cy.get('[href="/home"]').click()
    //cy.get('ul > :nth-child(1) > a').click()

  })
})